name: build-windows

on:
  workflow_dispatch:

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: cmake -S . -B build -DBUILD_TESTS=ON
      - name: Build
        run: cmake --build build --config Release --parallel
      - name: Add DLL directory to PATH
        run: echo "${{ github.workspace }}/build/Release" | Out-File -Append -FilePath $env:GITHUB_PATH
      - name: Test
        run: ctest --test-dir build --build-config Release --output-on-failure
